data:
  artifacts: artifacts
  content_dir: artifacts/content_img
  style_dir: artifacts/style_img
  gen_dir: artifacts/gen_img

weights:
  content_weight: 3e-8
  style_weight: 1e-3
  n_rows: 400
  n_iter: 10000
  learning_rate: 0.01
  vgg_weights: imagenet


